apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: meme-generator-tgb
  namespace: default
spec:
  targetGroupARN: PLACEHOLDER_TG_ARN
  targetType: ip
  serviceRef:
    name: meme-generator-service
    port: 80
